UICAL-148 use react-intl for date formatting
folio-org/ui-calendar pull request #340
Opened 2021-07-19 19:18 UTC by zburke

## Purpose

Some date display was pretty convoluted, storing formatters as translations and passing those to moment and passing that to `dateformat` and ... yeesh. 

## Approach

Use `react-intl` externally to present values to the UI, i.e. don't call `moment` functions for display. This resolves date strings like `01/20/AMAMAMAM` which passed the `dateFormat` translation value as an argument to `moment.format()`. This also allows the `dateformat` dependency to be removed completely. 

Additionally, use the localized value for `Closed`. It was always available, but we just weren't using it.

Finally, add `react-hot-loader` as a dev-dep and update `index.js` to support hot-loading. This is a standard practice for other modules that was missing here, but arguably that should be handled in a separate PR; LMK if you would prefer that. I didn't actually intend to include it here but forgot to split the changes on `package.json`. 

Refs [UICAL-148](https://issues.folio.org/browse/UICAL-148)

2021-07-20 12:12 UTC, Dmitriy-Litvinenko requested changes

2021-07-20 12:12 UTC, Dmitriy-Litvinenko commented on translations/ui-calendar/en.json
> -  "dateFormat":"MM/DD/YYYY",
Used in ui-calendar\stripes\ui-calendar\test\bigtest\helpers\messageConverters.js
We should change formatDateString before deleting dateFormat
Just for example `return date.format('MM/DD/YYYY');`

2021-07-20 12:12 UTC, Dmitriy-Litvinenko commented on src/settings/ServicePointDetails.js
> +                  {this.state.currentPeriod.startDate}
We have test error here "AssertionError: expected '7/25/2021-8/29/2021 (test)' to equal '07/25/2021 - 08/29/2021 (test)'"

2021-07-20 12:14 UTC, Dmitriy-Litvinenko commented
@zburke hello thank you for fix, but unfortunately we have problems with tests. I found 2 problems and add comment to them.

2021-07-20 12:39 UTC, zburke commented
Yeah, I should have let the tests run on the branch before tagging you for review, @Dmitriy-Litvinenko. Thanks for looking into this! I will try to get it cleaned up with minimal effort.

2021-07-21 09:12 UTC, Dmitriy-Litvinenko approved these changes

2021-07-21 10:59 UTC, merged