STRIPES-868 BREAKING bump react-intl to v6
folio-org/ui-calendar pull request #494
Opened 2023-09-11 21:25 UTC by zburke

Refs [UICAL-275](https://issues.folio.org/browse/UICAL-275)

2023-09-11 21:30 UTC, ncovercash commented
![image](https://github.com/folio-org/ui-calendar/assets/8005215/37ee6d0a-0074-47df-a243-0a4b659c6646)
a bit dramatic BREAKING, lol

2023-09-11 21:32 UTC, ncovercash requested changes
Can you bump the `package.json` version too?

2023-09-12 03:19 UTC, zburke commented
@ncovercash , I bumped the package version, but this PR will fail until somebody addresses [UICAL-271](https://issues.folio.org/browse/UICAL-271). That ticket wasn't meant to be a bug, but it sort of became one due to the @rehooks/local-storage patch release that same week that introduced rehooks/local-storage/issues/103. 

It's true the formatjs changelog is a little dramatic, but I love them for actually following the semver rules.

2023-09-21 19:27 UTC, ncovercash approved these changes

2023-09-21 23:10 UTC, danetsao approved these changes

2023-09-22 14:27 UTC, merged